language: python
python:
  - "2.7"
install: 
  - pip install --use-mirrors pyparsing
  - pip install --use-mirrors matplotlib
  - "python setup.py install"
script: nosetests
virtualenv:
  system_site_packages: true
before_install:
  - pip install numpy
  - pip install python-dateutil
  - pip install pytz
  - pip install scipy
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
virtualenv:
  system_site_packages: true
# command to install dependencies
script: true
