language: python
sudo: 'required'
python:
  - "2.7"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
install: 
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib scikit-learn
  - "python setup.py install"
virtualenv:
  system_site_packages: true
before_script:
  - wget http://downloads.sourceforge.net/project/spglib/spglib/spglib-1.6/spglib-1.6.0.tar.gz
  - tar -xvf spglib-1.6.0.tar.gz
  - cd spglib-1.6.0
  - ./configure
  - make
  - cd python/ase
  - python setup.py install
  - cd ../../..
  - mysql -e 'create database qmdb_dev;'
script:
  - cd qmpy/db
  - python manage.py syncdb --noinput
  - python manage.py test qmpy
