language: python
python:
  - "2.7"
before_install:
 - sudo apt-get install -qq python-numpy python-scipy
virtualenv:
  system_site_packages: true
# command to install dependencies
install: 
  - "python setup.py install"
# # command to run tests
script: 
  - "python qmpy/db/settings.py test"
