### Format ###
# host1:
#   binaries:
#       bin_name1: /path/to/bin1
#       bin_name2: /path/to/bin2
#   check_queue: /full/path/to/showq
#   hostname: full.host.name
#   ip_address: ###.###.##.###
#   nodes: # of nodes on machine
#   ppn: # of processors per node
#   sub_script: /full/path/to/submission/command
#   sub_text: filename for qfile to use a template.
#            A file named "filename" must be in configuration/qfiles
#   walltime: maximum walltime, in seconds
# host2: ...
    
edison_shared:
  binaries:
    vasp_535_O1: /global/homes/v/vih173/Codes/vasp_535_edison_O1_full
  check_queue: /usr/common/software/bin/sqs
  hostname: ''
  ip_address: 128.55.209.26
  nodes: 2000
  ppn: 12
  sub_script: /opt/slurm/default/bin/sbatch
  sub_text: edison_shared
  walltime: 172800
