### Format ###
# host1:
#   binaries:
#       bin_name1: /path/to/bin1
#       bin_name2: /path/to/bin2
#   check_queue: /full/path/to/showq
#   hostname: full.host.name
#   ip_address: ###.###.##.###
#   nodes: # of nodes on machine
#   ppn: # of processors per node
#   sub_script: /full/path/to/submission/command
#   sub_text: filename for qfile to use a template.
#            A file named "filename" must be in configuration/qfiles
#   walltime: maximum walltime, in seconds
# host2: ...
    
<<<<<<< HEAD
KNL:
=======
Comet:
  binaries: {}
  check_queue: qstat
  hostname: ''
  ip_address: 198.202.113.252
  nodes: 100
  ppn: 4
  sub_script: qsub
  sub_text: /home/jh2336/qtemplate/
  walltime: 86400
babbage:
>>>>>>> ca8b049cf0a069dfad285aae4258ffaac3deea64
  binaries:
    vasp_nersc: vasp_std
  check_queue: /usr/bin/squeue
  hostname: ''
<<<<<<< HEAD
  ip_address: 128.55.209.23
  nodes: 30000
  ppn: 64
  sub_script: /usr/bin/sbatch
  sub_text: knl_cori
  walltime: 86400
edison_alcc:
  binaries:
    vasp_hse: /project/projectdirs/m1673/Shahab/bin/vasp_edison_normal
  check_queue: /opt/slurm/default/bin/squeue
  hostname: ''
  ip_address: 128.55.209.26
  nodes: 30000
  ppn: 24
  sub_script: /opt/slurm/default/bin/sbatch
  sub_text: edison_alcc
  walltime: 86400
edison_shared:
=======
  ip_address: 129.105.1.128
  nodes: 24
  ppn: 4
  sub_script: /usr/local/bin/qsub
  sub_text: local
  walltime: 604800
byrd:
  binaries:
    vasp_53: /usr/local/bin/vasp_53
    vasp_53_serial: /usr/local/bin/vasp_53_serial
  check_queue: /usr/local/maui/bin/showq
  hostname: byrd.northwestern.edu
  ip_address: 165.124.29.202
  nodes: 33
  ppn: 8
  sub_script: /usr/local/bin/qsub
  sub_text: local
  walltime: 1382400
josquin:
  binaries:
    vasp_53: /usr/local/bin/vasp_53
    vasp_53_serial: /usr/local/bin/vasp_53_serial
  check_queue: /usr/local/maui/bin/showq
  hostname: josquin.northwestern.edu
  ip_address: 165.124.29.200
  nodes: 35
  ppn: 8
  sub_script: /usr/local/bin/qsub
  sub_text: local
  walltime: 1382400
p20746:
  binaries: {}
  check_queue: /usr/local/maui/bin/showq
  hostname: ''
  ip_address: null
  nodes: 200
  ppn: 8
  sub_script: ''
  sub_text: /usr/local/bin/qsub
  walltime: 86400
p20747:
  binaries: {}
  check_queue: /usr/local/maui/bin/showq
  hostname: ''
  ip_address: null
  nodes: 200
  ppn: 8
  sub_script: ''
  sub_text: /usr/local/bin/qsub
  walltime: 86400
palestrina:
  binaries:
    vasp_53: /usr/local/bin/vasp_53
    vasp_53_serial: /usr/local/bin/vasp_53_serial
  check_queue: /usr/local/maui/bin/showq
  hostname: palestrina.northwestern.edu
  ip_address: 129.105.61.89
  nodes: 32
  ppn: 8
  sub_script: /usr/local/bin/qsub
  sub_text: local
  walltime: 1382400
quest:
  binaries:
    vasp_53: /projects/b1004/bin/vasp_53
    vasp_53_serial: /projects/b1004/bin/vasp_53_serial
  check_queue: /opt/moab7/bin/showq
  hostname: ''
  ip_address: 165.124.130.20
  nodes: 200
  ppn: 4
  sub_script: /opt/moab7/bin/msub
  sub_text: quest
  walltime: 86400
stampede:
  binaries: {}
  check_queue: /usr/bin/squeue
  hostname: ''
  ip_address: 129.114.62.13
  nodes: 100
  ppn: 16
  sub_script: /usr/bin/sbatch
  sub_text: /home/oqmd/development/qmpy/qmpy/configuration/qfiles/stampede.q
  walltime: 86400
victoria:
>>>>>>> ca8b049cf0a069dfad285aae4258ffaac3deea64
  binaries:
    vasp_535_O1: /global/homes/v/vih173/Codes/vasp_535_edison_O1_full
  check_queue: /usr/common/software/bin/sqs
  hostname: ''
  ip_address: 128.55.209.26
  nodes: 2000
  ppn: 12
  sub_script: /opt/slurm/default/bin/sbatch
  sub_text: edison_shared
  walltime: 172800
